// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

namespace iced_x86::internal::regs_tbl {

constexpr std::size_t MAX_STRING_LENGTH = 5;
constexpr std::size_t VALID_STRING_LENGTH = 8;
constexpr std::size_t PADDING_SIZE = 5;
constexpr std::size_t REGS_DATA_SIZE = 1216;
/// Register names (one per `Register` value): a length byte followed by the ASCII chars. The last string is followed by
/// padding so it's possible to read `VALID_STRING_LENGTH` bytes from any string.
extern const std::uint8_t REGS_DATA[REGS_DATA_SIZE];

} // namespace iced_x86::internal::regs_tbl
