// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::nasm {

enum class CtorKind : std::uint8_t {
	Previous = 0,
	Normal_1 = 1,
	Normal_2 = 2,
	AamAad = 3,
	asz = 4,
	String = 5,
	STIG2_2b = 6,
	bcst = 7,
	bnd = 8,
	SignExt_4 = 9,
	DeclareData = 10,
	XLAT = 11,
	er_2 = 12,
	er_3 = 13,
	far = 14,
	far_mem = 15,
	invlpga = 16,
	maskmovq = 17,
	SignExt_3 = 18,
	STIG1 = 19,
	STIG2_2a = 20,
	movabs = 21,
	sae = 22,
	nop = 23,
	OpSize = 24,
	OpSize2_bnd = 25,
	OpSize3 = 26,
	os_2 = 27,
	os_3 = 28,
	os_call = 29,
	push_imm = 30,
	CC_1 = 31,
	CC_2 = 32,
	CC_3 = 33,
	os_jcc_a_1 = 34,
	os_jcc_a_2 = 35,
	os_jcc_a_3 = 36,
	os_jcc_b_1 = 37,
	os_jcc_b_2 = 38,
	os_jcc_b_3 = 39,
	os_loopcc = 40,
	os_loop = 41,
	os_mem = 42,
	os_mem_reg16 = 43,
	os_mem2 = 44,
	pblendvb = 45,
	push_imm8 = 46,
	pclmulqdq = 47,
	pops = 48,
	imul = 49,
	Reg16 = 50,
	Reg32 = 51,
	reverse = 52,
};

} // namespace iced_x86::internal::nasm
