// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::masm {

enum class CtorKind : std::uint8_t {
	Previous = 0,
	Normal_1 = 1,
	Normal_2 = 2,
	AamAad = 3,
	AX = 4,
	AY = 5,
	bnd = 6,
	STIG1 = 7,
	DeclareData = 8,
	DX = 9,
	fword = 10,
	Int3 = 11,
	imul = 12,
	invlpga = 13,
	CCa_1 = 14,
	CCa_2 = 15,
	CCa_3 = 16,
	CCb_1 = 17,
	CCb_2 = 18,
	CCb_3 = 19,
	jcc_1 = 20,
	jcc_2 = 21,
	jcc_3 = 22,
	Loopcc1 = 23,
	Loopcc2 = 24,
	maskmovq = 25,
	memsize = 26,
	YD = 27,
	YX = 28,
	monitor = 29,
	mwait = 30,
	mwaitx = 31,
	nop = 32,
	OpSize_1 = 33,
	OpSize_2 = 34,
	OpSize2 = 35,
	YA = 36,
	pblendvb = 37,
	pclmulqdq = 38,
	pops_2 = 39,
	pops_3 = 40,
	XY = 41,
	reg = 42,
	Reg16 = 43,
	Reg32 = 44,
	reverse = 45,
	ST_STi = 46,
	STi_ST = 47,
	XLAT = 48,
};

} // namespace iced_x86::internal::masm
