// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

namespace iced_x86::internal::masm {

/// Serialized formatter table data (one entry per `Code` value)
extern const std::uint8_t FORMATTER_TBL_DATA[];
/// Size of `FORMATTER_TBL_DATA` in bytes
extern const std::size_t FORMATTER_TBL_DATA_SIZE;

} // namespace iced_x86::internal::masm
