// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::gas {

enum class CtorKind : std::uint8_t {
	Previous = 0,
	Normal_1 = 1,
	Normal_2a = 2,
	Normal_2b = 3,
	Normal_2c = 4,
	Normal_3 = 5,
	AamAad = 6,
	asz = 7,
	bnd = 8,
	ST_STi = 9,
	DeclareData = 10,
	er_2 = 11,
	er_4 = 12,
	far = 13,
	imul = 14,
	maskmovq = 15,
	movabs = 16,
	nop = 17,
	OpSize = 18,
	OpSize2_bnd = 19,
	OpSize3 = 20,
	os = 21,
	STi_ST = 22,
	sae = 23,
	CC_1 = 24,
	CC_2 = 25,
	CC_3 = 26,
	os_jcc_1 = 27,
	os_jcc_2 = 28,
	os_jcc_3 = 29,
	os_loopcc = 30,
	os_loop = 31,
	os_mem = 32,
	Reg16 = 33,
	os_mem2 = 34,
	os2_3 = 35,
	os2_4 = 36,
	STIG1 = 37,
	pblendvb = 38,
	pclmulqdq = 39,
	pops = 40,
	mem16 = 41,
	Reg32 = 42,
};

} // namespace iced_x86::internal::gas
