// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

#include "internal/encoder/instruction_fmt.hpp"
#include "iced_x86/memory_size_ext.hpp"
#include "internal/encoder/mnemonic_str_tbl.hpp"
#include "internal/iced_assert.hpp"
#include "iced_x86/instruction.hpp"
#include "internal/mvex/mvex.hpp"

namespace iced_x86::internal {

static constexpr const char* CONV_FN_NAMES[13] = {
	"",
	"Sf32",
	"Sf64",
	"Si32",
	"Si64",
	"Uf32",
	"Uf64",
	"Ui32",
	"Ui64",
	"Df32",
	"Df64",
	"Di32",
	"Di64",
};

InstructionFormatter::InstructionFormatter(const OpCodeInfo& op_code, InstrStrFmtOption fmt_opt, std::string& sb) noexcept
	: op_code(op_code), sb(sb), r32_count(0), r64_count(0), bnd_count(0), start_op_index(0), r32_index(0), r64_index(0), bnd_index(0), k_index(0),
	  vec_index(0), tmm_index(0), op_count(op_code.op_count()), op_mask_is_k1(false), no_vec_index(false), swap_vec_index_12(false),
	  no_gpr_suffix(false), vec_index_same_as_op_index(false) {
	switch (fmt_opt) {
	case InstrStrFmtOption::None:
		break;
	case InstrStrFmtOption::OpMaskIsK1_or_NoGprSuffix:
		op_mask_is_k1 = true;
		no_gpr_suffix = true;
		break;
	case InstrStrFmtOption::IncVecIndex:
		vec_index++;
		break;
	case InstrStrFmtOption::NoVecIndex:
		no_vec_index = true;
		break;
	case InstrStrFmtOption::SwapVecIndex12:
		swap_vec_index_12 = true;
		break;
	case InstrStrFmtOption::SkipOp0:
		start_op_index = 1;
		break;
	case InstrStrFmtOption::VecIndexSameAsOpIndex:
		vec_index_same_as_op_index = true;
		break;
	}
	if ((op_code.op0_kind() == OpCodeOperandKind::k_reg || op_code.op0_kind() == OpCodeOperandKind::kp1_reg) && op_code.op_count() > 2 &&
		op_code.encoding() != EncodingKind::MVEX)
		vec_index_same_as_op_index = true;
	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		switch (op_kind) {
		case OpCodeOperandKind::r32_reg:
		case OpCodeOperandKind::r32_reg_mem:
		case OpCodeOperandKind::r32_rm:
		case OpCodeOperandKind::r32_opcode:
		case OpCodeOperandKind::r32_vvvv:
			r32_count++;
			break;

		case OpCodeOperandKind::r64_reg:
		case OpCodeOperandKind::r64_reg_mem:
		case OpCodeOperandKind::r64_rm:
		case OpCodeOperandKind::r64_opcode:
		case OpCodeOperandKind::r64_vvvv:
			r64_count++;
			break;

		case OpCodeOperandKind::bnd_or_mem_mpx:
		case OpCodeOperandKind::bnd_reg:
			bnd_count++;
			break;

		case OpCodeOperandKind::seg_rSI:
		case OpCodeOperandKind::es_rDI:
		case OpCodeOperandKind::seg_rBX_al:
			// string instructions, xlat
			op_count = 0;
			break;

		default:
			break;
		}
	}
}

std::uint32_t InstructionFormatter::get_k_index() noexcept {
	k_index++;
	if (op_mask_is_k1) {
		if (k_index == 1)
			return 2;
		if (k_index == 2)
			return 1;
	}
	return k_index;
}

std::uint32_t InstructionFormatter::get_bnd_index() noexcept {
	if (bnd_count <= 1)
		return 0;
	bnd_index++;
	return bnd_index;
}

std::uint32_t InstructionFormatter::get_vec_index(std::uint32_t op_index) noexcept {
	if (no_vec_index)
		return 0;
	if (vec_index_same_as_op_index)
		return op_index + 1;
	vec_index++;
	if (swap_vec_index_12) {
		if (vec_index == 1)
			return 2;
		if (vec_index == 2)
			return 1;
	}
	return vec_index;
}

std::uint32_t InstructionFormatter::get_tmm_index() noexcept {
	tmm_index++;
	return tmm_index;
}

MemorySize InstructionFormatter::get_memory_size(bool is_broadcast) const noexcept {
	const std::size_t code = static_cast<std::size_t>(op_code.code());
	if (is_broadcast)
		return SIZES_BCST[code];
	return SIZES_NORMAL[code];
}

std::string InstructionFormatter::format() {
	if (!op_code.is_instruction()) {
		switch (op_code.code()) {
		// GENERATOR-BEGIN: InstrFmtNotInstructionString
		// ⚠️This was generated by GENERATOR!🦹‍♂️
		case Code::INVALID:
			return std::string("<invalid>");
		case Code::DeclareByte:
			return std::string("<db>");
		case Code::DeclareWord:
			return std::string("<dw>");
		case Code::DeclareDword:
			return std::string("<dd>");
		case Code::DeclareQword:
			return std::string("<dq>");
		case Code::Zero_bytes:
			return std::string("ZERO_BYTES");
		// GENERATOR-END: InstrFmtNotInstructionString
		default:
			ICED_UNREACHABLE();
		}
	}

	sb.clear();

	write(TO_MNEMONIC_STR[static_cast<std::size_t>(op_code.mnemonic())], true);
	if (start_op_index < op_count) {
		sb.push_back(' ');
		std::uint32_t sae_er_index = op_count - 1;
		if (op_code.encoding() != EncodingKind::Legacy && op_code.op_kind(sae_er_index) == OpCodeOperandKind::imm8)
			sae_er_index--;
		bool add_comma = false;
		for (std::uint32_t i = start_op_index; i < op_count; i++) {
			std::uint32_t tmp;
			if (add_comma)
				write_op_separator();
			add_comma = true;

			if (i == sae_er_index && op_code.encoding() == EncodingKind::MVEX) {
				const MvexConvFn conv_fn = get_mvex_info(op_code.code()).conv_fn;
				if (conv_fn != MvexConvFn::None) {
					sb.append(CONV_FN_NAMES[static_cast<std::size_t>(conv_fn)]);
					sb.push_back('(');
				}
			}
			const OpCodeOperandKind op_kind = op_code.op_kind(i);
			switch (op_kind) {
			case OpCodeOperandKind::farbr2_2:
				sb.append("ptr16:16");
				break;
			case OpCodeOperandKind::farbr4_2:
				sb.append("ptr16:32");
				break;

			case OpCodeOperandKind::mem_offs:
				sb.append("moffs");
				write_memory_size(get_memory_size(false));
				break;

			case OpCodeOperandKind::mem:
			case OpCodeOperandKind::mem_mpx:
				write_memory();
				break;
			case OpCodeOperandKind::sibmem:
				sb.append("sibmem");
				break;
			case OpCodeOperandKind::mem_mib:
				sb.append("mib");
				break;

			case OpCodeOperandKind::mem_vsib32x:
				sb.append("vm32x");
				break;
			case OpCodeOperandKind::mem_vsib64x:
				sb.append("vm64x");
				break;
			case OpCodeOperandKind::mem_vsib32y:
				sb.append("vm32y");
				break;
			case OpCodeOperandKind::mem_vsib64y:
				sb.append("vm64y");
				break;
			case OpCodeOperandKind::mem_vsib32z:
				if (op_code.encoding() == EncodingKind::MVEX)
					sb.append("mvt");
				else
					sb.append("vm32z");
				break;
			case OpCodeOperandKind::mem_vsib64z:
				sb.append("vm64z");
				break;
			case OpCodeOperandKind::r8_or_mem:
				write_gpr_mem(8);
				break;
			case OpCodeOperandKind::r16_or_mem:
				write_gpr_mem(16);
				break;
			case OpCodeOperandKind::r32_or_mem:
			case OpCodeOperandKind::r32_or_mem_mpx:
				write_gpr_mem(32);
				break;
			case OpCodeOperandKind::r64_or_mem:
			case OpCodeOperandKind::r64_or_mem_mpx:
				write_gpr_mem(64);
				break;

			case OpCodeOperandKind::mm_or_mem:
				tmp = get_vec_index(i);
				write_reg_mem("mm", tmp);
				break;

			case OpCodeOperandKind::xmm_or_mem:
				tmp = get_vec_index(i);
				write_reg_mem("xmm", tmp);
				break;

			case OpCodeOperandKind::ymm_or_mem:
				tmp = get_vec_index(i);
				write_reg_mem("ymm", tmp);
				break;

			case OpCodeOperandKind::zmm_or_mem:
				tmp = get_vec_index(i);
				write_reg_mem("zmm", tmp);
				break;

			case OpCodeOperandKind::bnd_or_mem_mpx:
				tmp = get_bnd_index();
				write_reg_op2("bnd", tmp);
				sb.push_back('/');
				write_memory();
				break;

			case OpCodeOperandKind::k_or_mem:
				tmp = get_k_index();
				write_reg_mem("k", tmp);
				break;

			case OpCodeOperandKind::r8_reg:
			case OpCodeOperandKind::r8_opcode:
				write_reg_op1("r8");
				break;
			case OpCodeOperandKind::r16_reg:
			case OpCodeOperandKind::r16_reg_mem:
			case OpCodeOperandKind::r16_rm:
			case OpCodeOperandKind::r16_opcode:
				write_reg_op1("r16");
				break;

			case OpCodeOperandKind::r32_reg:
			case OpCodeOperandKind::r32_reg_mem:
			case OpCodeOperandKind::r32_rm:
			case OpCodeOperandKind::r32_opcode:
			case OpCodeOperandKind::r32_vvvv:
				write_reg_op1("r32");
				append_gpr_suffix(r32_count, r32_index);
				break;

			case OpCodeOperandKind::r64_reg:
			case OpCodeOperandKind::r64_reg_mem:
			case OpCodeOperandKind::r64_rm:
			case OpCodeOperandKind::r64_opcode:
			case OpCodeOperandKind::r64_vvvv:
				write_reg_op1("r64");
				append_gpr_suffix(r64_count, r64_index);
				break;

			case OpCodeOperandKind::seg_reg:
				sb.append("Sreg");
				break;
			case OpCodeOperandKind::k_reg:
			case OpCodeOperandKind::k_rm:
			case OpCodeOperandKind::k_vvvv:
				tmp = get_k_index();
				write_reg_op2("k", tmp);
				break;

			case OpCodeOperandKind::kp1_reg:
				tmp = get_k_index();
				write_reg_op2("k", tmp);
				sb.append("+1");
				break;

			case OpCodeOperandKind::mm_reg:
			case OpCodeOperandKind::mm_rm:
				tmp = get_vec_index(i);
				write_reg_op2("mm", tmp);
				break;

			case OpCodeOperandKind::xmm_reg:
			case OpCodeOperandKind::xmm_rm:
			case OpCodeOperandKind::xmm_vvvv:
			case OpCodeOperandKind::xmm_is4:
			case OpCodeOperandKind::xmm_is5:
				tmp = get_vec_index(i);
				write_reg_op2("xmm", tmp);
				break;

			case OpCodeOperandKind::xmmp3_vvvv:
				tmp = get_vec_index(i);
				write_reg_op2("xmm", tmp);
				sb.append("+3");
				break;

			case OpCodeOperandKind::ymm_reg:
			case OpCodeOperandKind::ymm_rm:
			case OpCodeOperandKind::ymm_vvvv:
			case OpCodeOperandKind::ymm_is4:
			case OpCodeOperandKind::ymm_is5:
				tmp = get_vec_index(i);
				write_reg_op2("ymm", tmp);
				break;

			case OpCodeOperandKind::zmm_reg:
			case OpCodeOperandKind::zmm_rm:
			case OpCodeOperandKind::zmm_vvvv:
				tmp = get_vec_index(i);
				write_reg_op2("zmm", tmp);
				break;

			case OpCodeOperandKind::zmmp3_vvvv:
				tmp = get_vec_index(i);
				write_reg_op2("zmm", tmp);
				sb.append("+3");
				break;

			case OpCodeOperandKind::tmm_reg:
			case OpCodeOperandKind::tmm_rm:
			case OpCodeOperandKind::tmm_vvvv:
				tmp = get_tmm_index();
				write_reg_op2("tmm", tmp);
				break;

			case OpCodeOperandKind::bnd_reg:
				tmp = get_bnd_index();
				write_reg_op2("bnd", tmp);
				break;

			case OpCodeOperandKind::cr_reg:
				write_reg_op1("cr");
				break;
			case OpCodeOperandKind::dr_reg:
				write_reg_op1("dr");
				break;
			case OpCodeOperandKind::tr_reg:
				write_reg_op1("tr");
				break;
			case OpCodeOperandKind::es:
				write_register("es");
				break;
			case OpCodeOperandKind::cs:
				write_register("cs");
				break;
			case OpCodeOperandKind::ss:
				write_register("ss");
				break;
			case OpCodeOperandKind::ds:
				write_register("ds");
				break;
			case OpCodeOperandKind::fs:
				write_register("fs");
				break;
			case OpCodeOperandKind::gs:
				write_register("gs");
				break;
			case OpCodeOperandKind::al:
				write_register("al");
				break;
			case OpCodeOperandKind::cl:
				write_register("cl");
				break;
			case OpCodeOperandKind::ax:
				write_register("ax");
				break;
			case OpCodeOperandKind::dx:
				write_register("dx");
				break;
			case OpCodeOperandKind::eax:
				write_register("eax");
				break;
			case OpCodeOperandKind::rax:
				write_register("rax");
				break;

			case OpCodeOperandKind::st0:
			case OpCodeOperandKind::sti_opcode:
				write_register("ST");
				if (op_kind == OpCodeOperandKind::st0) {
					switch (op_code.code()) {
					case Code::Fcomi_st0_sti:
					case Code::Fcomip_st0_sti:
					case Code::Fucomi_st0_sti:
					case Code::Fucomip_st0_sti:
						break;
					default:
						sb.append("(0)");
						break;
					}
				}
				else {
					ICED_DEBUG_ASSERT(op_kind == OpCodeOperandKind::sti_opcode);
					sb.append("(i)");
				}
				break;

			case OpCodeOperandKind::imm4_m2z:
				sb.append("imm4");
				break;

			case OpCodeOperandKind::imm8:
			case OpCodeOperandKind::imm8sex16:
			case OpCodeOperandKind::imm8sex32:
			case OpCodeOperandKind::imm8sex64:
				sb.append("imm8");
				break;
			case OpCodeOperandKind::imm8_const_1:
				sb.push_back('1');
				break;
			case OpCodeOperandKind::imm16:
				sb.append("imm16");
				break;
			case OpCodeOperandKind::imm32:
			case OpCodeOperandKind::imm32sex64:
				sb.append("imm32");
				break;
			case OpCodeOperandKind::imm64:
				sb.append("imm64");
				break;

			case OpCodeOperandKind::seg_rSI:
			case OpCodeOperandKind::es_rDI:
			case OpCodeOperandKind::seg_rDI:
			case OpCodeOperandKind::seg_rBX_al:
				add_comma = false;
				break;

			case OpCodeOperandKind::br16_1:
			case OpCodeOperandKind::br32_1:
			case OpCodeOperandKind::br64_1:
				sb.append("rel8");
				break;
			case OpCodeOperandKind::br16_2:
			case OpCodeOperandKind::xbegin_2:
				sb.append("rel16");
				break;
			case OpCodeOperandKind::br32_4:
			case OpCodeOperandKind::br64_4:
			case OpCodeOperandKind::xbegin_4:
				sb.append("rel32");
				break;
			case OpCodeOperandKind::brdisp_2:
				sb.append("disp16");
				break;
			case OpCodeOperandKind::brdisp_4:
				sb.append("disp32");
				break;
			case OpCodeOperandKind::None:
			default:
				ICED_UNREACHABLE();
			}

			if (i == sae_er_index && op_code.encoding() == EncodingKind::MVEX) {
				const MvexConvFn conv_fn = get_mvex_info(op_code.code()).conv_fn;
				if (conv_fn != MvexConvFn::None)
					sb.push_back(')');
			}
			if (i == 0) {
				if (op_code.can_use_op_mask_register()) {
					sb.push_back(' ');
					tmp = get_k_index();
					write_reg_decorator("k", tmp);
					if (op_code.can_use_zeroing_masking())
						write_decorator("z");
				}
			}
			if (i == sae_er_index && op_code.encoding() != EncodingKind::MVEX) {
				if (op_code.can_suppress_all_exceptions())
					write_decorator("sae");
				if (op_code.can_use_rounding_control())
					write_decorator("er");
			}
		}
	}

	switch (op_code.code()) {
	// GENERATOR-BEGIN: PrintImpliedOps
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	case Code::Tpause_r32:
	case Code::Tpause_r64:
	case Code::Umwait_r32:
	case Code::Umwait_r64:
		write_op_separator();
		write("<EDX>", false);
		write_op_separator();
		write("<EAX>", false);
		break;
	case Code::Pblendvb_xmm_xmmm128:
	case Code::Blendvps_xmm_xmmm128:
	case Code::Blendvpd_xmm_xmmm128:
	case Code::Sha256rnds2_xmm_xmmm128:
		write_op_separator();
		write("<XMM0>", true);
		break;
	case Code::Aesencwide128kl_m384:
	case Code::Aesdecwide128kl_m384:
	case Code::Aesencwide256kl_m512:
	case Code::Aesdecwide256kl_m512:
		write_op_separator();
		write("<XMM0-7>", true);
		break;
	case Code::Loadiwkey_xmm_xmm:
		write_op_separator();
		write("<EAX>", true);
		write_op_separator();
		write("<XMM0>", true);
		break;
	case Code::Encodekey128_r32_r32:
		write_op_separator();
		write("<XMM0-2>", true);
		write_op_separator();
		write("<XMM4-6>", true);
		break;
	case Code::Encodekey256_r32_r32:
		write_op_separator();
		write("<XMM0-6>", true);
		break;
	case Code::Hreset_imm8:
		write_op_separator();
		write("<EAX>", true);
		break;
	// GENERATOR-END: PrintImpliedOps

	default:
		break;
	}

	return sb;
}

void InstructionFormatter::write_memory_size(MemorySize memory_size) {
	switch (op_code.code()) {
	case Code::Fldcw_m2byte:
	case Code::Fnstcw_m2byte:
	case Code::Fstcw_m2byte:
	case Code::Fnstsw_m2byte:
	case Code::Fstsw_m2byte:
		sb.append("2byte");
		return;
	default:
		break;
	}

	switch (memory_size) {
	case MemorySize::Bound16_WordWord:
		sb.append("16&16");
		break;
	case MemorySize::Bound32_DwordDword:
		sb.append("32&32");
		break;
	case MemorySize::FpuEnv14:
		sb.append("14byte");
		break;
	case MemorySize::FpuEnv28:
		sb.append("28byte");
		break;
	case MemorySize::FpuState94:
		sb.append("94byte");
		break;
	case MemorySize::FpuState108:
		sb.append("108byte");
		break;
	case MemorySize::Fxsave_512Byte:
	case MemorySize::Fxsave64_512Byte:
		sb.append("512byte");
		break;
	case MemorySize::Xsave:
	case MemorySize::Xsave64:
		// 'm' has already been appended
		sb.append("em");
		break;
	case MemorySize::SegPtr16:
		sb.append("16:16");
		break;
	case MemorySize::SegPtr32:
		sb.append("16:32");
		break;
	case MemorySize::SegPtr64:
		sb.append("16:64");
		break;

	case MemorySize::Fword6:
		if (!is_sgdt_or_sidt())
			sb.append("16&32");
		break;

	case MemorySize::Fword10:
		if (!is_sgdt_or_sidt())
			sb.append("16&64");
		break;

	default: {
		const std::size_t mem_size = memory_size_ext::size(memory_size);
		if (mem_size != 0)
			sb.append(std::to_string(mem_size * 8));
		break;
	}
	}

	if (is_fpu_instruction(op_code.code())) {
		switch (memory_size) {
		case MemorySize::Int16:
		case MemorySize::Int32:
		case MemorySize::Int64:
			sb.append("int");
			break;
		case MemorySize::Float32:
		case MemorySize::Float64:
		case MemorySize::Float80:
			sb.append("fp");
			break;
		case MemorySize::Bcd:
			sb.append("bcd");
			break;
		default:
			break;
		}
	}
}

bool InstructionFormatter::is_sgdt_or_sidt() const noexcept {
	switch (op_code.code()) {
	case Code::Sgdt_m1632_16:
	case Code::Sgdt_m1632:
	case Code::Sgdt_m1664:
	case Code::Sidt_m1632_16:
	case Code::Sidt_m1632:
	case Code::Sidt_m1664:
		return true;
	default:
		return false;
	}
}

void InstructionFormatter::write_register(const char* register_) { write(register_, true); }

void InstructionFormatter::write_reg_op1(const char* register_) { write(register_, false); }

void InstructionFormatter::write_reg_op2(const char* register_, std::uint32_t index) {
	write_reg_op1(register_);
	if (index > 0)
		sb.append(std::to_string(index));
}

void InstructionFormatter::write_decorator(const char* decorator) {
	sb.push_back('{');
	write(decorator, false);
	sb.push_back('}');
}

void InstructionFormatter::write_reg_decorator(const char* register_, std::uint32_t index) {
	sb.push_back('{');
	write(register_, false);
	sb.append(std::to_string(index));
	sb.push_back('}');
}

void InstructionFormatter::append_gpr_suffix(std::uint32_t count, std::uint32_t& index) {
	if (count <= 1 || no_gpr_suffix)
		return;
	sb.push_back(static_cast<char>('a' + index));
	index++;
}

void InstructionFormatter::write_op_separator() { sb.append(", "); }

void InstructionFormatter::write(const char* s, bool upper) {
	// All strings are ASCII
	if (upper) {
		for (; *s != 0; s++) {
			const char c = *s;
			sb.push_back(c >= 'a' && c <= 'z' ? static_cast<char>(c - 'a' + 'A') : c);
		}
	}
	else {
		for (; *s != 0; s++) {
			const char c = *s;
			sb.push_back(c >= 'A' && c <= 'Z' ? static_cast<char>(c - 'A' + 'a') : c);
		}
	}
}

void InstructionFormatter::write_gpr_mem(std::uint32_t reg_size) {
	ICED_DEBUG_ASSERT(!op_code.can_broadcast());
	sb.push_back('r');
	const std::size_t mem_size = memory_size_ext::size(get_memory_size(false)) * 8;
	if (mem_size != reg_size)
		sb.append(std::to_string(reg_size));
	sb.push_back('/');
	write_memory();
}

void InstructionFormatter::write_reg_mem(const char* register_, std::uint32_t index) {
	write_reg_op2(register_, index);
	sb.push_back('/');
	write_memory();
}

void InstructionFormatter::write_memory() {
	write_memory1(false);
	if (op_code.can_broadcast()) {
		sb.push_back('/');
		write_memory1(true);
	}
}

void InstructionFormatter::write_memory1(bool is_broadcast) {
	const MemorySize memory_size = get_memory_size(is_broadcast);
	sb.push_back('m');
	if (op_code.encoding() == EncodingKind::MVEX) {
		const MvexInfo& mvex = get_mvex_info(op_code.code());
		if (mvex.eh_bit == MvexEHBit::None && !mvex.ignores_eviction_hint())
			sb.push_back('t');
	}
	write_memory_size(memory_size);
	if (is_broadcast)
		sb.append("bcst");
}

bool InstructionFormatter::is_fpu_instruction(Code code) noexcept {
	return static_cast<std::uint32_t>(code) - static_cast<std::uint32_t>(Code::Fadd_m32fp) <=
		static_cast<std::uint32_t>(Code::Fcomip_st0_sti) - static_cast<std::uint32_t>(Code::Fadd_m32fp);
}

} // namespace iced_x86::internal
