// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

#include "internal/encoder/op_code_fmt.hpp"
#include "internal/iced_assert.hpp"
#include "internal/mvex/mvex_info.hpp"

namespace iced_x86::internal {

std::string OpCodeFormatter::format() {
	if (!op_code.is_instruction()) {
		switch (op_code.code()) {
		// GENERATOR-BEGIN: OpCodeFmtNotInstructionString
		// ⚠️This was generated by GENERATOR!🦹‍♂️
		case Code::INVALID:
			return std::string("<invalid>");
		case Code::DeclareByte:
			return std::string("<db>");
		case Code::DeclareWord:
			return std::string("<dw>");
		case Code::DeclareDword:
			return std::string("<dd>");
		case Code::DeclareQword:
			return std::string("<dq>");
		case Code::Zero_bytes:
			return std::string("<zero_bytes>");
		// GENERATOR-END: OpCodeFmtNotInstructionString
		default:
			ICED_UNREACHABLE();
		}
	}
	switch (op_code.encoding()) {
	case EncodingKind::Legacy:
		return format_legacy();
	case EncodingKind::VEX:
		return format_vec_encoding("VEX");
	case EncodingKind::EVEX:
		return format_vec_encoding("EVEX");
	case EncodingKind::XOP:
		return format_vec_encoding("XOP");
	case EncodingKind::D3NOW:
		return format_3dnow();
	case EncodingKind::MVEX:
		return format_vec_encoding("MVEX");
	default:
		ICED_UNREACHABLE();
	}
}

void OpCodeFormatter::append_hex_byte(std::uint8_t value) {
	static constexpr char HEX[] = "0123456789ABCDEF";
	sb.push_back(HEX[value >> 4]);
	sb.push_back(HEX[value & 0xF]);
}

void OpCodeFormatter::append_op_code(std::uint32_t value, std::uint32_t value_len, bool sep) {
	if (value_len == 1)
		append_hex_byte(static_cast<std::uint8_t>(value));
	else {
		ICED_DEBUG_ASSERT(value_len == 2);
		append_hex_byte(static_cast<std::uint8_t>(value >> 8));
		if (sep)
			sb.push_back(' ');
		append_hex_byte(static_cast<std::uint8_t>(value));
	}
}

void OpCodeFormatter::append_table(bool sep) {
	switch (op_code.table()) {
	case OpCodeTableKind::Normal:
		break;
	case OpCodeTableKind::T0F:
		append_op_code(0x0F, 1, sep);
		break;
	case OpCodeTableKind::T0F38:
		append_op_code(0x0F38, 2, sep);
		break;
	case OpCodeTableKind::T0F3A:
		append_op_code(0x0F3A, 2, sep);
		break;
	case OpCodeTableKind::MAP5:
		sb.append("MAP5");
		break;
	case OpCodeTableKind::MAP6:
		sb.append("MAP6");
		break;
	case OpCodeTableKind::MAP8:
		sb.append("X8");
		break;
	case OpCodeTableKind::MAP9:
		sb.append("X9");
		break;
	case OpCodeTableKind::MAP10:
		sb.append("XA");
		break;
	}
}

bool OpCodeFormatter::has_mod_rm() const noexcept {
	const std::uint32_t op_count = op_code.op_count();
	if (op_count == 0)
		return false;

	switch (op_code.encoding()) {
	case EncodingKind::Legacy:
	case EncodingKind::VEX:
		break;
	case EncodingKind::EVEX:
	case EncodingKind::XOP:
	case EncodingKind::D3NOW:
	case EncodingKind::MVEX:
		return true;
	}

	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		switch (op_kind) {
		// GENERATOR-BEGIN: HasModRM
		// ⚠️This was generated by GENERATOR!🦹‍♂️
		case OpCodeOperandKind::mem:
		case OpCodeOperandKind::mem_mpx:
		case OpCodeOperandKind::mem_mib:
		case OpCodeOperandKind::mem_vsib32x:
		case OpCodeOperandKind::mem_vsib64x:
		case OpCodeOperandKind::mem_vsib32y:
		case OpCodeOperandKind::mem_vsib64y:
		case OpCodeOperandKind::mem_vsib32z:
		case OpCodeOperandKind::mem_vsib64z:
		case OpCodeOperandKind::r8_or_mem:
		case OpCodeOperandKind::r16_or_mem:
		case OpCodeOperandKind::r32_or_mem:
		case OpCodeOperandKind::r32_or_mem_mpx:
		case OpCodeOperandKind::r64_or_mem:
		case OpCodeOperandKind::r64_or_mem_mpx:
		case OpCodeOperandKind::mm_or_mem:
		case OpCodeOperandKind::xmm_or_mem:
		case OpCodeOperandKind::ymm_or_mem:
		case OpCodeOperandKind::zmm_or_mem:
		case OpCodeOperandKind::bnd_or_mem_mpx:
		case OpCodeOperandKind::k_or_mem:
		case OpCodeOperandKind::r8_reg:
		case OpCodeOperandKind::r16_reg:
		case OpCodeOperandKind::r16_reg_mem:
		case OpCodeOperandKind::r16_rm:
		case OpCodeOperandKind::r32_reg:
		case OpCodeOperandKind::r32_reg_mem:
		case OpCodeOperandKind::r32_rm:
		case OpCodeOperandKind::r64_reg:
		case OpCodeOperandKind::r64_reg_mem:
		case OpCodeOperandKind::r64_rm:
		case OpCodeOperandKind::seg_reg:
		case OpCodeOperandKind::k_reg:
		case OpCodeOperandKind::kp1_reg:
		case OpCodeOperandKind::k_rm:
		case OpCodeOperandKind::mm_reg:
		case OpCodeOperandKind::mm_rm:
		case OpCodeOperandKind::xmm_reg:
		case OpCodeOperandKind::xmm_rm:
		case OpCodeOperandKind::ymm_reg:
		case OpCodeOperandKind::ymm_rm:
		case OpCodeOperandKind::zmm_reg:
		case OpCodeOperandKind::zmm_rm:
		case OpCodeOperandKind::cr_reg:
		case OpCodeOperandKind::dr_reg:
		case OpCodeOperandKind::tr_reg:
		case OpCodeOperandKind::bnd_reg:
		case OpCodeOperandKind::sibmem:
		case OpCodeOperandKind::tmm_reg:
		case OpCodeOperandKind::tmm_rm:
			return true;
		// GENERATOR-END: HasModRM

		default:
			break;
		}
	}
	return false;
}

bool OpCodeFormatter::has_vsib() const noexcept {
	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		switch (op_kind) {
		// GENERATOR-BEGIN: HasVsib
		// ⚠️This was generated by GENERATOR!🦹‍♂️
		case OpCodeOperandKind::mem_vsib32x:
		case OpCodeOperandKind::mem_vsib64x:
		case OpCodeOperandKind::mem_vsib32y:
		case OpCodeOperandKind::mem_vsib64y:
		case OpCodeOperandKind::mem_vsib32z:
		case OpCodeOperandKind::mem_vsib64z:
			return true;
		// GENERATOR-END: HasVsib

		default:
			break;
		}
	}
	return false;
}

OpCodeOperandKind OpCodeFormatter::get_op_code_bits_operand() const noexcept {
	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		switch (op_kind) {
		case OpCodeOperandKind::r8_opcode:
		case OpCodeOperandKind::r16_opcode:
		case OpCodeOperandKind::r32_opcode:
		case OpCodeOperandKind::r64_opcode:
			return op_kind;
		default:
			break;
		}
	}
	return OpCodeOperandKind::None;
}

std::optional<OpCodeFormatter::ModrmInfo> OpCodeFormatter::get_modrm_info() const noexcept {
	bool is_reg_only = true;
	const std::int32_t rrr = op_code.group_index();
	std::int32_t bbb = op_code.rm_group_index();
	if (!has_modrm_info)
		return std::nullopt;
	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		switch (op_kind) {
		case OpCodeOperandKind::mem_offs:
		case OpCodeOperandKind::mem:
		case OpCodeOperandKind::mem_mpx:
		case OpCodeOperandKind::mem_mib:
			is_reg_only = false;
			break;
		case OpCodeOperandKind::mem_vsib32x:
		case OpCodeOperandKind::mem_vsib64x:
		case OpCodeOperandKind::mem_vsib32y:
		case OpCodeOperandKind::mem_vsib64y:
		case OpCodeOperandKind::mem_vsib32z:
		case OpCodeOperandKind::mem_vsib64z:
		case OpCodeOperandKind::sibmem:
			is_reg_only = false;
			bbb = 4;
			break;
		default:
			break;
		}
	}
	return ModrmInfo{is_reg_only, rrr, bbb};
}

void OpCodeFormatter::append_bits(const char* name, std::int32_t bits, std::uint32_t num_bits) {
	if (bits < 0)
		sb.append(name);
	else {
		for (std::uint32_t bit = num_bits; bit > 0; bit--)
			sb.push_back(((bits >> (bit - 1)) & 1) != 0 ? '1' : '0');
	}
}

void OpCodeFormatter::append_rest() {
	if (auto modrm_info = get_modrm_info()) {
		sb.append(modrm_info->is_reg_only ? " 11:" : " !(11):");
		append_bits("rrr", modrm_info->rrr, 3);
		sb.push_back(':');
		append_bits("bbb", modrm_info->bbb, 3);
	}
	else {
		const bool is_vsib = (op_code.encoding() == EncodingKind::EVEX || op_code.encoding() == EncodingKind::MVEX) && has_vsib();
		if (op_code.is_group()) {
			sb.append(" /");
			sb.append(std::to_string(op_code.group_index()));
		}
		else if (!is_vsib && has_mod_rm())
			sb.append(" /r");
		if (is_vsib)
			sb.append(" /vsib");
	}

	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		switch (op_kind) {
		case OpCodeOperandKind::br16_1:
		case OpCodeOperandKind::br32_1:
		case OpCodeOperandKind::br64_1:
			sb.append(" cb");
			break;

		case OpCodeOperandKind::br16_2:
		case OpCodeOperandKind::xbegin_2:
		case OpCodeOperandKind::brdisp_2:
			sb.append(" cw");
			break;

		case OpCodeOperandKind::farbr2_2:
		case OpCodeOperandKind::br32_4:
		case OpCodeOperandKind::br64_4:
		case OpCodeOperandKind::xbegin_4:
		case OpCodeOperandKind::brdisp_4:
			sb.append(" cd");
			break;

		case OpCodeOperandKind::farbr4_2:
			sb.append(" cp");
			break;

		case OpCodeOperandKind::imm8:
		case OpCodeOperandKind::imm8sex16:
		case OpCodeOperandKind::imm8sex32:
		case OpCodeOperandKind::imm8sex64:
			sb.append(" ib");
			break;

		case OpCodeOperandKind::imm16:
			sb.append(" iw");
			break;

		case OpCodeOperandKind::imm32:
		case OpCodeOperandKind::imm32sex64:
			sb.append(" id");
			break;

		case OpCodeOperandKind::imm64:
			sb.append(" io");
			break;

		case OpCodeOperandKind::xmm_is4:
		case OpCodeOperandKind::ymm_is4:
			sb.append(" /is4");
			break;

		case OpCodeOperandKind::xmm_is5:
		case OpCodeOperandKind::ymm_is5:
			sb.append(" /is5");
			// don't show the next imm8
			return;

		case OpCodeOperandKind::mem_offs:
			sb.append(" mo");
			break;

		default:
			break;
		}
	}
}

std::string OpCodeFormatter::format_legacy() {
	sb.clear();

	if (op_code.fwait()) {
		append_hex_byte(0x9B);
		sb.push_back(' ');
	}

	switch (op_code.address_size()) {
	case 0:
		break;
	case 16:
		sb.append("a16 ");
		break;
	case 32:
		sb.append("a32 ");
		break;
	case 64:
		sb.append("a64 ");
		break;
	default:
		ICED_UNREACHABLE();
	}

	switch (op_code.operand_size()) {
	case 0:
		break;
	case 16:
		sb.append("o16 ");
		break;
	case 32:
		sb.append("o32 ");
		break;
	case 64:
		// o64 (REX.W) must be immediately before the opcode and is handled below
		break;
	default:
		ICED_UNREACHABLE();
	}

	switch (op_code.mandatory_prefix()) {
	case MandatoryPrefix::None:
		break;
	case MandatoryPrefix::PNP:
		sb.append("NP ");
		break;
	case MandatoryPrefix::P66:
		append_hex_byte(0x66);
		sb.push_back(' ');
		break;
	case MandatoryPrefix::PF3:
		append_hex_byte(0xF3);
		sb.push_back(' ');
		break;
	case MandatoryPrefix::PF2:
		append_hex_byte(0xF2);
		sb.push_back(' ');
		break;
	}

	if (op_code.operand_size() == 64)
		sb.append("o64 ");

	append_table(true);
	if (op_code.table() != OpCodeTableKind::Normal)
		sb.push_back(' ');
	append_op_code(op_code.op_code(), op_code.op_code_len(), true);
	switch (get_op_code_bits_operand()) {
	case OpCodeOperandKind::r8_opcode:
		sb.append("+rb");
		break;
	case OpCodeOperandKind::r16_opcode:
		sb.append("+rw");
		break;
	case OpCodeOperandKind::r32_opcode:
		sb.append("+rd");
		break;
	case OpCodeOperandKind::r64_opcode:
		sb.append("+ro");
		break;
	case OpCodeOperandKind::None:
		break;
	default:
		ICED_UNREACHABLE();
	}
	for (const OpCodeOperandKind op_kind : op_code.op_kinds()) {
		if (op_kind == OpCodeOperandKind::sti_opcode) {
			sb.append("+i");
			break;
		}
	}

	append_rest();

	return sb;
}

std::string OpCodeFormatter::format_3dnow() {
	sb.clear();

	append_op_code(0x0F0F, 2, true);
	sb.append(" /r");
	sb.push_back(' ');
	append_op_code(op_code.op_code(), op_code.op_code_len(), true);

	return sb;
}

std::string OpCodeFormatter::format_vec_encoding(const char* encoding_name) {
	sb.clear();

	sb.append(encoding_name);
	if (op_code.encoding() == EncodingKind::MVEX) {
		const MvexInfo& mvex = get_mvex_info(op_code.code());
		if (mvex.is_ndd())
			sb.append(".NDD");
		else if (mvex.is_nds())
			sb.append(".NDS");
	}
	sb.push_back('.');
	if (op_code.is_lig())
		sb.append("LIG");
	else {
		switch (lkind) {
		case LKind::L128:
			sb.append(std::to_string(128U << op_code.l()));
			break;
		case LKind::L0:
			sb.push_back('L');
			sb.append(std::to_string(op_code.l()));
			break;
		case LKind::LZ:
			if (op_code.l() != 0)
				ICED_UNREACHABLE();
			sb.append("LZ");
			break;
		case LKind::None:
		default:
			ICED_UNREACHABLE();
		}
	}
	switch (op_code.mandatory_prefix()) {
	case MandatoryPrefix::None:
	case MandatoryPrefix::PNP:
		break;
	case MandatoryPrefix::P66:
		sb.push_back('.');
		append_hex_byte(0x66);
		break;
	case MandatoryPrefix::PF3:
		sb.push_back('.');
		append_hex_byte(0xF3);
		break;
	case MandatoryPrefix::PF2:
		sb.push_back('.');
		append_hex_byte(0xF2);
		break;
	}
	if (op_code.table() != OpCodeTableKind::Normal)
		sb.push_back('.');
	append_table(false);
	if (op_code.is_wig())
		sb.append(".WIG");
	else {
		sb.append(".W");
		sb.append(std::to_string(op_code.w()));
	}
	if (op_code.encoding() == EncodingKind::MVEX) {
		switch (get_mvex_info(op_code.code()).eh_bit) {
		case MvexEHBit::None:
			break;
		case MvexEHBit::EH0:
			sb.append(".EH0");
			break;
		case MvexEHBit::EH1:
			sb.append(".EH1");
			break;
		}
	}
	sb.push_back(' ');
	append_op_code(op_code.op_code(), op_code.op_code_len(), true);
	append_rest();

	return sb;
}

} // namespace iced_x86::internal
