// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#include "iced_x86/code_asm/registers.hpp"
#include "iced_x86/register_ext.hpp"

namespace iced_x86::code_asm::registers {

std::optional<AsmRegister8> gpr8::get_gpr8(Register register_) noexcept {
	if (register_ext::is_gpr8(register_))
		return AsmRegister8(register_);
	return std::nullopt;
}

std::optional<AsmRegister16> gpr16::get_gpr16(Register register_) noexcept {
	if (register_ext::is_gpr16(register_))
		return AsmRegister16(register_);
	return std::nullopt;
}

std::optional<AsmRegister32> gpr32::get_gpr32(Register register_) noexcept {
	if (register_ext::is_gpr32(register_))
		return AsmRegister32(register_);
	return std::nullopt;
}

std::optional<AsmRegister64> gpr64::get_gpr64(Register register_) noexcept {
	if (register_ext::is_gpr64(register_))
		return AsmRegister64(register_);
	return std::nullopt;
}

std::optional<AsmRegisterSegment> segment::get_segment(Register register_) noexcept {
	if (register_ext::is_segment_register(register_))
		return AsmRegisterSegment(register_);
	return std::nullopt;
}

std::optional<AsmRegisterSt> st::get_st(Register register_) noexcept {
	if (register_ext::is_st(register_))
		return AsmRegisterSt(register_);
	return std::nullopt;
}

std::optional<AsmRegisterCr> cr::get_cr(Register register_) noexcept {
	if (register_ext::is_cr(register_))
		return AsmRegisterCr(register_);
	return std::nullopt;
}

std::optional<AsmRegisterDr> dr::get_dr(Register register_) noexcept {
	if (register_ext::is_dr(register_))
		return AsmRegisterDr(register_);
	return std::nullopt;
}

std::optional<AsmRegisterTr> tr::get_tr(Register register_) noexcept {
	if (register_ext::is_tr(register_))
		return AsmRegisterTr(register_);
	return std::nullopt;
}

std::optional<AsmRegisterBnd> bnd::get_bnd(Register register_) noexcept {
	if (register_ext::is_bnd(register_))
		return AsmRegisterBnd(register_);
	return std::nullopt;
}

std::optional<AsmRegisterK> k::get_k(Register register_) noexcept {
	if (register_ext::is_k(register_))
		return AsmRegisterK(register_);
	return std::nullopt;
}

std::optional<AsmRegisterMm> mm::get_mm(Register register_) noexcept {
	if (register_ext::is_mm(register_))
		return AsmRegisterMm(register_);
	return std::nullopt;
}

std::optional<AsmRegisterXmm> xmm::get_xmm(Register register_) noexcept {
	if (register_ext::is_xmm(register_))
		return AsmRegisterXmm(register_);
	return std::nullopt;
}

std::optional<AsmRegisterYmm> ymm::get_ymm(Register register_) noexcept {
	if (register_ext::is_ymm(register_))
		return AsmRegisterYmm(register_);
	return std::nullopt;
}

std::optional<AsmRegisterZmm> zmm::get_zmm(Register register_) noexcept {
	if (register_ext::is_zmm(register_))
		return AsmRegisterZmm(register_);
	return std::nullopt;
}

std::optional<AsmRegisterTmm> tmm::get_tmm(Register register_) noexcept {
	if (register_ext::is_tmm(register_))
		return AsmRegisterTmm(register_);
	return std::nullopt;
}

} // namespace iced_x86::code_asm::registers
