// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

namespace iced_x86::internal::decoder_data_xop {

extern const std::uint8_t TBL_DATA[];
extern const std::size_t TBL_DATA_SIZE;
constexpr std::size_t MAX_ID_NAMES = 7;
constexpr std::size_t HANDLERS_MAP8_INDEX = 4;
constexpr std::size_t HANDLERS_MAP9_INDEX = 5;
constexpr std::size_t HANDLERS_MAP10_INDEX = 6;

} // namespace iced_x86::internal::decoder_data_xop
