// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

namespace iced_x86::internal::decoder_data_legacy {

extern const std::uint8_t TBL_DATA[];
extern const std::size_t TBL_DATA_SIZE;
constexpr std::size_t MAX_ID_NAMES = 82;
constexpr std::size_t HANDLERS_MAP0_INDEX = 81;

} // namespace iced_x86::internal::decoder_data_legacy
