// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstddef>
#include <cstdint>

namespace iced_x86::internal::decoder_data_vex {

extern const std::uint8_t TBL_DATA[];
extern const std::size_t TBL_DATA_SIZE;
constexpr std::size_t MAX_ID_NAMES = 16;
constexpr std::size_t HANDLERS_MAP0_INDEX = 14;
constexpr std::size_t HANDLERS_0F_INDEX = 15;
constexpr std::size_t HANDLERS_0F38_INDEX = 12;
constexpr std::size_t HANDLERS_0F3A_INDEX = 13;

} // namespace iced_x86::internal::decoder_data_vex
