// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class MvexOpCodeHandlerKind : std::uint8_t {
	Invalid = 0,
	Invalid2 = 1,
	Dup = 2,
	HandlerReference = 3,
	ArrayReference = 4,
	RM = 5,
	Group = 6,
	W = 7,
	MandatoryPrefix2 = 8,
	EH = 9,
	M = 10,
	MV = 11,
	VW = 12,
	HWIb = 13,
	VWIb = 14,
	VHW = 15,
	VHWIb = 16,
	VKW = 17,
	KHW = 18,
	KHWIb = 19,
	VSIB = 20,
	VSIB_V = 21,
	V_VSIB = 22,
};

} // namespace iced_x86::internal
