// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

enum class SerializedDataKind : std::uint8_t {
	HandlerReference = 0,
	ArrayReference = 1,
};

} // namespace iced_x86::internal
