// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal {

extern const std::uint32_t ENC_FLAGS1[4936];
extern const std::uint32_t ENC_FLAGS2[4936];
extern const std::uint32_t ENC_FLAGS3[4936];

} // namespace iced_x86::internal
