// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

// Only included by src/encoder/op_code_handler.cpp

#include "internal/encoder/ops.hpp"

namespace iced_x86::internal {

static constexpr InvalidOpHandler NONE{};
static constexpr OprDI OPR_DI{};
static constexpr OpA OP_A_2{2};
static constexpr OpA OP_A_4{4};
static constexpr OpHx OP_HX_EAX_R15_D{Register::EAX, Register::R15D};
static constexpr OpHx OP_HX_K0_K7{Register::K0, Register::K7};
static constexpr OpHx OP_HX_RAX_R15{Register::RAX, Register::R15};
static constexpr OpHx OP_HX_TMM0_TMM7{Register::TMM0, Register::TMM7};
static constexpr OpHx OP_HX_XMM0_XMM15{Register::XMM0, Register::XMM15};
static constexpr OpHx OP_HX_XMM0_XMM31{Register::XMM0, Register::XMM31};
static constexpr OpHx OP_HX_YMM0_YMM15{Register::YMM0, Register::YMM15};
static constexpr OpHx OP_HX_YMM0_YMM31{Register::YMM0, Register::YMM31};
static constexpr OpHx OP_HX_ZMM0_ZMM31{Register::ZMM0, Register::ZMM31};
static constexpr OpI4 OP_I4{};
static constexpr OpIb OP_IB_IMMEDIATE8{OpKind::Immediate8};
static constexpr OpIb OP_IB_IMMEDIATE8TO16{OpKind::Immediate8to16};
static constexpr OpIb OP_IB_IMMEDIATE8TO32{OpKind::Immediate8to32};
static constexpr OpIb OP_IB_IMMEDIATE8TO64{OpKind::Immediate8to64};
static constexpr OpId OP_ID_IMMEDIATE32{OpKind::Immediate32};
static constexpr OpId OP_ID_IMMEDIATE32TO64{OpKind::Immediate32to64};
static constexpr OpImm OP_IMM_1{1};
static constexpr OpIq OP_IQ{};
static constexpr OpIsX OP_IS_X_XMM0_XMM15{Register::XMM0, Register::XMM15};
static constexpr OpIsX OP_IS_X_YMM0_YMM15{Register::YMM0, Register::YMM15};
static constexpr OpIw OP_IW{};
static constexpr OpJdisp OP_JDISP_2{2};
static constexpr OpJdisp OP_JDISP_4{4};
static constexpr OpJx OP_JX_2{2};
static constexpr OpJx OP_JX_4{4};
static constexpr OpJ OP_J_NEAR_BRANCH16_1{OpKind::NearBranch16, 1};
static constexpr OpJ OP_J_NEAR_BRANCH16_2{OpKind::NearBranch16, 2};
static constexpr OpJ OP_J_NEAR_BRANCH32_1{OpKind::NearBranch32, 1};
static constexpr OpJ OP_J_NEAR_BRANCH32_4{OpKind::NearBranch32, 4};
static constexpr OpJ OP_J_NEAR_BRANCH64_1{OpKind::NearBranch64, 1};
static constexpr OpJ OP_J_NEAR_BRANCH64_4{OpKind::NearBranch64, 4};
static constexpr OpModRM_reg OP_MOD_RM_REG_AL_R15_L{Register::AL, Register::R15L};
static constexpr OpModRM_reg OP_MOD_RM_REG_AX_R15_W{Register::AX, Register::R15W};
static constexpr OpModRM_reg OP_MOD_RM_REG_BND0_BND3{Register::BND0, Register::BND3};
static constexpr OpModRM_reg OP_MOD_RM_REG_DR0_DR15{Register::DR0, Register::DR15};
static constexpr OpModRM_reg OP_MOD_RM_REG_EAX_R15_D{Register::EAX, Register::R15D};
static constexpr OpModRM_reg OP_MOD_RM_REG_ES_GS{Register::ES, Register::GS};
static constexpr OpModRM_regF0 OP_MOD_RM_REG_F0_CR0_CR15{Register::CR0, Register::CR15};
static constexpr OpModRM_reg OP_MOD_RM_REG_K0_K7{Register::K0, Register::K7};
static constexpr OpModRM_reg_mem OP_MOD_RM_REG_MEM_AX_R15_W{Register::AX, Register::R15W};
static constexpr OpModRM_reg_mem OP_MOD_RM_REG_MEM_EAX_R15_D{Register::EAX, Register::R15D};
static constexpr OpModRM_reg_mem OP_MOD_RM_REG_MEM_RAX_R15{Register::RAX, Register::R15};
static constexpr OpModRM_reg OP_MOD_RM_REG_MM0_MM7{Register::MM0, Register::MM7};
static constexpr OpModRM_reg OP_MOD_RM_REG_RAX_R15{Register::RAX, Register::R15};
static constexpr OpModRM_reg OP_MOD_RM_REG_TMM0_TMM7{Register::TMM0, Register::TMM7};
static constexpr OpModRM_reg OP_MOD_RM_REG_TR0_TR7{Register::TR0, Register::TR7};
static constexpr OpModRM_reg OP_MOD_RM_REG_XMM0_XMM15{Register::XMM0, Register::XMM15};
static constexpr OpModRM_reg OP_MOD_RM_REG_XMM0_XMM31{Register::XMM0, Register::XMM31};
static constexpr OpModRM_reg OP_MOD_RM_REG_YMM0_YMM15{Register::YMM0, Register::YMM15};
static constexpr OpModRM_reg OP_MOD_RM_REG_YMM0_YMM31{Register::YMM0, Register::YMM31};
static constexpr OpModRM_reg OP_MOD_RM_REG_ZMM0_ZMM31{Register::ZMM0, Register::ZMM31};
static constexpr OpModRM_rm OP_MOD_RM_RM_AL_R15_L{Register::AL, Register::R15L};
static constexpr OpModRM_rm OP_MOD_RM_RM_AX_R15_W{Register::AX, Register::R15W};
static constexpr OpModRM_rm OP_MOD_RM_RM_BND0_BND3{Register::BND0, Register::BND3};
static constexpr OpModRM_rm OP_MOD_RM_RM_EAX_R15_D{Register::EAX, Register::R15D};
static constexpr OpModRM_rm OP_MOD_RM_RM_K0_K7{Register::K0, Register::K7};
static constexpr OpModRM_rm_mem_only OP_MOD_RM_RM_MEM_ONLY_FALSE{false};
static constexpr OpModRM_rm_mem_only OP_MOD_RM_RM_MEM_ONLY_TRUE{true};
static constexpr OpModRM_rm OP_MOD_RM_RM_MM0_MM7{Register::MM0, Register::MM7};
static constexpr OpModRM_rm OP_MOD_RM_RM_RAX_R15{Register::RAX, Register::R15};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_AX_R15_W{Register::AX, Register::R15W};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_EAX_R15_D{Register::EAX, Register::R15D};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_K0_K7{Register::K0, Register::K7};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_MM0_MM7{Register::MM0, Register::MM7};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_RAX_R15{Register::RAX, Register::R15};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_TMM0_TMM7{Register::TMM0, Register::TMM7};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_XMM0_XMM15{Register::XMM0, Register::XMM15};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_XMM0_XMM31{Register::XMM0, Register::XMM31};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_YMM0_YMM15{Register::YMM0, Register::YMM15};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_YMM0_YMM31{Register::YMM0, Register::YMM31};
static constexpr OpModRM_rm_reg_only OP_MOD_RM_RM_REG_ONLY_ZMM0_ZMM31{Register::ZMM0, Register::ZMM31};
static constexpr OpModRM_rm OP_MOD_RM_RM_XMM0_XMM15{Register::XMM0, Register::XMM15};
static constexpr OpModRM_rm OP_MOD_RM_RM_XMM0_XMM31{Register::XMM0, Register::XMM31};
static constexpr OpModRM_rm OP_MOD_RM_RM_YMM0_YMM15{Register::YMM0, Register::YMM15};
static constexpr OpModRM_rm OP_MOD_RM_RM_YMM0_YMM31{Register::YMM0, Register::YMM31};
static constexpr OpModRM_rm OP_MOD_RM_RM_ZMM0_ZMM31{Register::ZMM0, Register::ZMM31};
static constexpr OpMRBX OP_MRBX{};
static constexpr OpO OP_O{};
static constexpr OpReg OP_REG_AL{Register::AL};
static constexpr OpReg OP_REG_AX{Register::AX};
static constexpr OpReg OP_REG_CL{Register::CL};
static constexpr OpReg OP_REG_CS{Register::CS};
static constexpr OpReg OP_REG_DS{Register::DS};
static constexpr OpReg OP_REG_DX{Register::DX};
static constexpr OpReg OP_REG_EAX{Register::EAX};
static constexpr OpRegEmbed8 OP_REG_EMBED8_AL_R15_L{Register::AL, Register::R15L};
static constexpr OpRegEmbed8 OP_REG_EMBED8_AX_R15_W{Register::AX, Register::R15W};
static constexpr OpRegEmbed8 OP_REG_EMBED8_EAX_R15_D{Register::EAX, Register::R15D};
static constexpr OpRegEmbed8 OP_REG_EMBED8_RAX_R15{Register::RAX, Register::R15};
static constexpr OpReg OP_REG_ES{Register::ES};
static constexpr OpReg OP_REG_FS{Register::FS};
static constexpr OpReg OP_REG_GS{Register::GS};
static constexpr OpReg OP_REG_RAX{Register::RAX};
static constexpr OpReg OP_REG_SS{Register::SS};
static constexpr OpReg OP_REG_ST0{Register::ST0};
static constexpr OpRegSTi OP_REG_STI{};
static constexpr OpVsib OP_VSIB_XMM0_XMM15{Register::XMM0, Register::XMM15};
static constexpr OpVsib OP_VSIB_XMM0_XMM31{Register::XMM0, Register::XMM31};
static constexpr OpVsib OP_VSIB_YMM0_YMM15{Register::YMM0, Register::YMM15};
static constexpr OpVsib OP_VSIB_YMM0_YMM31{Register::YMM0, Register::YMM31};
static constexpr OpVsib OP_VSIB_ZMM0_ZMM31{Register::ZMM0, Register::ZMM31};
static constexpr OpX OP_X{};
static constexpr OpY OP_Y{};

static constexpr const Op* LEGACY_TABLE[76] = {
	&NONE,// None
	&OP_A_2,// farbr2_2
	&OP_A_4,// farbr4_2
	&OP_O,// mem_offs
	&OP_MOD_RM_RM_MEM_ONLY_FALSE,// mem
	&OP_MOD_RM_RM_MEM_ONLY_FALSE,// mem_mpx
	&OP_MOD_RM_RM_MEM_ONLY_FALSE,// mem_mib
	&OP_MOD_RM_RM_AL_R15_L,// r8_or_mem
	&OP_MOD_RM_RM_AX_R15_W,// r16_or_mem
	&OP_MOD_RM_RM_EAX_R15_D,// r32_or_mem
	&OP_MOD_RM_RM_EAX_R15_D,// r32_or_mem_mpx
	&OP_MOD_RM_RM_RAX_R15,// r64_or_mem
	&OP_MOD_RM_RM_RAX_R15,// r64_or_mem_mpx
	&OP_MOD_RM_RM_MM0_MM7,// mm_or_mem
	&OP_MOD_RM_RM_XMM0_XMM15,// xmm_or_mem
	&OP_MOD_RM_RM_BND0_BND3,// bnd_or_mem_mpx
	&OP_MOD_RM_REG_AL_R15_L,// r8_reg
	&OP_REG_EMBED8_AL_R15_L,// r8_opcode
	&OP_MOD_RM_REG_AX_R15_W,// r16_reg
	&OP_MOD_RM_REG_MEM_AX_R15_W,// r16_reg_mem
	&OP_MOD_RM_RM_REG_ONLY_AX_R15_W,// r16_rm
	&OP_REG_EMBED8_AX_R15_W,// r16_opcode
	&OP_MOD_RM_REG_EAX_R15_D,// r32_reg
	&OP_MOD_RM_REG_MEM_EAX_R15_D,// r32_reg_mem
	&OP_MOD_RM_RM_REG_ONLY_EAX_R15_D,// r32_rm
	&OP_REG_EMBED8_EAX_R15_D,// r32_opcode
	&OP_MOD_RM_REG_RAX_R15,// r64_reg
	&OP_MOD_RM_REG_MEM_RAX_R15,// r64_reg_mem
	&OP_MOD_RM_RM_REG_ONLY_RAX_R15,// r64_rm
	&OP_REG_EMBED8_RAX_R15,// r64_opcode
	&OP_MOD_RM_REG_ES_GS,// seg_reg
	&OP_MOD_RM_REG_MM0_MM7,// mm_reg
	&OP_MOD_RM_RM_REG_ONLY_MM0_MM7,// mm_rm
	&OP_MOD_RM_REG_XMM0_XMM15,// xmm_reg
	&OP_MOD_RM_RM_REG_ONLY_XMM0_XMM15,// xmm_rm
	&OP_MOD_RM_REG_F0_CR0_CR15,// cr_reg
	&OP_MOD_RM_REG_DR0_DR15,// dr_reg
	&OP_MOD_RM_REG_TR0_TR7,// tr_reg
	&OP_MOD_RM_REG_BND0_BND3,// bnd_reg
	&OP_REG_ES,// es
	&OP_REG_CS,// cs
	&OP_REG_SS,// ss
	&OP_REG_DS,// ds
	&OP_REG_FS,// fs
	&OP_REG_GS,// gs
	&OP_REG_AL,// al
	&OP_REG_CL,// cl
	&OP_REG_AX,// ax
	&OP_REG_DX,// dx
	&OP_REG_EAX,// eax
	&OP_REG_RAX,// rax
	&OP_REG_ST0,// st0
	&OP_REG_STI,// sti_opcode
	&OP_IB_IMMEDIATE8,// imm8
	&OP_IMM_1,// imm8_const_1
	&OP_IB_IMMEDIATE8TO16,// imm8sex16
	&OP_IB_IMMEDIATE8TO32,// imm8sex32
	&OP_IB_IMMEDIATE8TO64,// imm8sex64
	&OP_IW,// imm16
	&OP_ID_IMMEDIATE32,// imm32
	&OP_ID_IMMEDIATE32TO64,// imm32sex64
	&OP_IQ,// imm64
	&OP_X,// seg_rSI
	&OP_Y,// es_rDI
	&OPR_DI,// seg_rDI
	&OP_MRBX,// seg_rBX_al
	&OP_J_NEAR_BRANCH16_1,// br16_1
	&OP_J_NEAR_BRANCH32_1,// br32_1
	&OP_J_NEAR_BRANCH64_1,// br64_1
	&OP_J_NEAR_BRANCH16_2,// br16_2
	&OP_J_NEAR_BRANCH32_4,// br32_4
	&OP_J_NEAR_BRANCH64_4,// br64_4
	&OP_JX_2,// xbegin_2
	&OP_JX_4,// xbegin_4
	&OP_JDISP_2,// brdisp_2
	&OP_JDISP_4,// brdisp_4
};

static constexpr const Op* VEX_TABLE[39] = {
	&NONE,// None
	&OP_MOD_RM_RM_MEM_ONLY_FALSE,// mem
	&OP_VSIB_XMM0_XMM15,// mem_vsib32x
	&OP_VSIB_XMM0_XMM15,// mem_vsib64x
	&OP_VSIB_YMM0_YMM15,// mem_vsib32y
	&OP_VSIB_YMM0_YMM15,// mem_vsib64y
	&OP_MOD_RM_RM_EAX_R15_D,// r32_or_mem
	&OP_MOD_RM_RM_RAX_R15,// r64_or_mem
	&OP_MOD_RM_RM_XMM0_XMM15,// xmm_or_mem
	&OP_MOD_RM_RM_YMM0_YMM15,// ymm_or_mem
	&OP_MOD_RM_RM_K0_K7,// k_or_mem
	&OP_MOD_RM_REG_EAX_R15_D,// r32_reg
	&OP_MOD_RM_RM_REG_ONLY_EAX_R15_D,// r32_rm
	&OP_HX_EAX_R15_D,// r32_vvvv
	&OP_MOD_RM_REG_RAX_R15,// r64_reg
	&OP_MOD_RM_RM_REG_ONLY_RAX_R15,// r64_rm
	&OP_HX_RAX_R15,// r64_vvvv
	&OP_MOD_RM_REG_K0_K7,// k_reg
	&OP_MOD_RM_RM_REG_ONLY_K0_K7,// k_rm
	&OP_HX_K0_K7,// k_vvvv
	&OP_MOD_RM_REG_XMM0_XMM15,// xmm_reg
	&OP_MOD_RM_RM_REG_ONLY_XMM0_XMM15,// xmm_rm
	&OP_HX_XMM0_XMM15,// xmm_vvvv
	&OP_IS_X_XMM0_XMM15,// xmm_is4
	&OP_IS_X_XMM0_XMM15,// xmm_is5
	&OP_MOD_RM_REG_YMM0_YMM15,// ymm_reg
	&OP_MOD_RM_RM_REG_ONLY_YMM0_YMM15,// ymm_rm
	&OP_HX_YMM0_YMM15,// ymm_vvvv
	&OP_IS_X_YMM0_YMM15,// ymm_is4
	&OP_IS_X_YMM0_YMM15,// ymm_is5
	&OP_I4,// imm4_m2z
	&OP_IB_IMMEDIATE8,// imm8
	&OPR_DI,// seg_rDI
	&OP_J_NEAR_BRANCH64_1,// br64_1
	&OP_J_NEAR_BRANCH64_4,// br64_4
	&OP_MOD_RM_RM_MEM_ONLY_TRUE,// sibmem
	&OP_MOD_RM_REG_TMM0_TMM7,// tmm_reg
	&OP_MOD_RM_RM_REG_ONLY_TMM0_TMM7,// tmm_rm
	&OP_HX_TMM0_TMM7,// tmm_vvvv
};

static constexpr const Op* XOP_TABLE[19] = {
	&NONE,// None
	&OP_MOD_RM_RM_EAX_R15_D,// r32_or_mem
	&OP_MOD_RM_RM_RAX_R15,// r64_or_mem
	&OP_MOD_RM_RM_XMM0_XMM15,// xmm_or_mem
	&OP_MOD_RM_RM_YMM0_YMM15,// ymm_or_mem
	&OP_MOD_RM_REG_EAX_R15_D,// r32_reg
	&OP_MOD_RM_RM_REG_ONLY_EAX_R15_D,// r32_rm
	&OP_HX_EAX_R15_D,// r32_vvvv
	&OP_MOD_RM_REG_RAX_R15,// r64_reg
	&OP_MOD_RM_RM_REG_ONLY_RAX_R15,// r64_rm
	&OP_HX_RAX_R15,// r64_vvvv
	&OP_MOD_RM_REG_XMM0_XMM15,// xmm_reg
	&OP_HX_XMM0_XMM15,// xmm_vvvv
	&OP_IS_X_XMM0_XMM15,// xmm_is4
	&OP_MOD_RM_REG_YMM0_YMM15,// ymm_reg
	&OP_HX_YMM0_YMM15,// ymm_vvvv
	&OP_IS_X_YMM0_YMM15,// ymm_is4
	&OP_IB_IMMEDIATE8,// imm8
	&OP_ID_IMMEDIATE32,// imm32
};

static constexpr const Op* EVEX_TABLE[32] = {
	&NONE,// None
	&OP_MOD_RM_RM_MEM_ONLY_FALSE,// mem
	&OP_VSIB_XMM0_XMM31,// mem_vsib32x
	&OP_VSIB_XMM0_XMM31,// mem_vsib64x
	&OP_VSIB_YMM0_YMM31,// mem_vsib32y
	&OP_VSIB_YMM0_YMM31,// mem_vsib64y
	&OP_VSIB_ZMM0_ZMM31,// mem_vsib32z
	&OP_VSIB_ZMM0_ZMM31,// mem_vsib64z
	&OP_MOD_RM_RM_EAX_R15_D,// r32_or_mem
	&OP_MOD_RM_RM_RAX_R15,// r64_or_mem
	&OP_MOD_RM_RM_XMM0_XMM31,// xmm_or_mem
	&OP_MOD_RM_RM_YMM0_YMM31,// ymm_or_mem
	&OP_MOD_RM_RM_ZMM0_ZMM31,// zmm_or_mem
	&OP_MOD_RM_REG_EAX_R15_D,// r32_reg
	&OP_MOD_RM_RM_REG_ONLY_EAX_R15_D,// r32_rm
	&OP_MOD_RM_REG_RAX_R15,// r64_reg
	&OP_MOD_RM_RM_REG_ONLY_RAX_R15,// r64_rm
	&OP_MOD_RM_REG_K0_K7,// k_reg
	&OP_MOD_RM_REG_K0_K7,// kp1_reg
	&OP_MOD_RM_RM_REG_ONLY_K0_K7,// k_rm
	&OP_MOD_RM_REG_XMM0_XMM31,// xmm_reg
	&OP_MOD_RM_RM_REG_ONLY_XMM0_XMM31,// xmm_rm
	&OP_HX_XMM0_XMM31,// xmm_vvvv
	&OP_HX_XMM0_XMM31,// xmmp3_vvvv
	&OP_MOD_RM_REG_YMM0_YMM31,// ymm_reg
	&OP_MOD_RM_RM_REG_ONLY_YMM0_YMM31,// ymm_rm
	&OP_HX_YMM0_YMM31,// ymm_vvvv
	&OP_MOD_RM_REG_ZMM0_ZMM31,// zmm_reg
	&OP_MOD_RM_RM_REG_ONLY_ZMM0_ZMM31,// zmm_rm
	&OP_HX_ZMM0_ZMM31,// zmm_vvvv
	&OP_HX_ZMM0_ZMM31,// zmmp3_vvvv
	&OP_IB_IMMEDIATE8,// imm8
};

static constexpr const Op* MVEX_TABLE[9] = {
	&NONE,// None
	&OP_MOD_RM_RM_MEM_ONLY_FALSE,// mem
	&OP_VSIB_ZMM0_ZMM31,// mem_vsib32z
	&OP_MOD_RM_RM_ZMM0_ZMM31,// zmm_or_mem
	&OP_MOD_RM_REG_K0_K7,// k_reg
	&OP_HX_K0_K7,// k_vvvv
	&OP_MOD_RM_REG_ZMM0_ZMM31,// zmm_reg
	&OP_HX_ZMM0_ZMM31,// zmm_vvvv
	&OP_IB_IMMEDIATE8,// imm8
};

} // namespace iced_x86::internal
