// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

using System.Linq;
using Generator.Enums;
using Generator.Enums.Encoder;
using Generator.IO;
using Generator.Tables;

namespace Generator.Encoder.Cpp {
	/// <summary>
	/// Generates the tables that are created by the encoder generator but are needed by the C++ core (always compiled):
	/// the MVEX tables (<c>src/mvex/*.cpp</c>, Rust: <c>mvex/mvex_data.rs</c>, <c>mvex_tt_lut.rs</c>, <c>mvex_memsz_lut.rs</c>)
	/// and the VSIB instructions (<c>Instruction::vsib()</c>).
	/// The encoder's own tables are generated by the C++ encoder generator.
	/// </summary>
	[Generator(TargetLanguage.Cpp)]
	sealed class CppEncoderCoreTablesGenerator : EncoderGenerator {
		readonly IdentifierConverter idConverter;

		public CppEncoderCoreTablesGenerator(GeneratorContext generatorContext)
			: base(generatorContext.Types) {
			idConverter = CppIdentifierConverter.Create();
		}

		protected override void Generate(EnumType enumType) { }
		protected override void Generate(OpCodeHandlers handlers) { }
		protected override void Generate((EnumValue value, uint size)[] immSizes) { }
		protected override void GenerateInstructionFormatter((EnumValue code, string result)[] notInstrStrings) { }
		protected override void GenerateOpCodeFormatter((EnumValue code, string result)[] notInstrStrings, EnumValue[] hasModRM, EnumValue[] hasVsib) { }
		protected override void GenerateCore() { }
		protected override void GenerateInstrSwitch(EnumValue[] jccInstr, EnumValue[] simpleBranchInstr, EnumValue[] callInstr, EnumValue[] jmpInstr, EnumValue[] xbeginInstr) { }
		protected override void GenerateDecoderOptionsTable((EnumValue decOptionValue, EnumValue decoderOptions)[] values) { }
		protected override void GenerateImpliedOps((EncodingKind Encoding, InstrStrImpliedOp[] Ops, InstructionDef[] defs)[] impliedOpsInfo) { }

		protected override void GenerateOpCodeInfo(InstructionDef[] defs, (MvexTupleTypeLutKind ttLutKind, EnumValue[] tupleTypes)[] mvexTupleTypeData,
			(MvexTupleTypeLutKind ttLutKind, EnumValue[] tupleTypes)[] mvexMemorySizeData) {
			var mvexInfos = GetData(defs).Where(a => a.mvex is not null && a.def.Encoding == EncodingKind.MVEX).Select(a => (a.def, a.mvex.GetValueOrDefault())).ToArray();
			GenerateMvexInfo(mvexInfos);
			GenerateLut(mvexTupleTypeData, "mvex_tt_lut.cpp", "MVEX_TUPLE_TYPE_LUT");
			GenerateLut(mvexMemorySizeData, "mvex_memsz_lut.cpp", "MVEX_MEMSZ_LUT");
		}

		void GenerateMvexInfo((InstructionDef def, MvexEncInfo mvex)[] infos) {
			var filename = CppConstants.GetSrcFilename(genTypes, "mvex", "mvex_data.cpp");
			using (var writer = new FileWriter(TargetLanguage.Cpp, FileUtils.OpenWrite(filename))) {
				writer.WriteFileHeader();
				writer.WriteLine("#include \"internal/mvex/mvex.hpp\"");
				writer.WriteLine();
				CppConstants.WriteNamespaceBegin(writer, CppConstants.InternalNamespace);
				writer.WriteLine($"const MvexInfo MVEX_INFO[{infos.Length}] = {{");
				using (writer.Indent()) {
					foreach (var (def, mvex) in infos)
						writer.WriteLine($"MvexInfo({CppConstants.ToEnumValue(idConverter, mvex.TupleTypeLutKind)}, {CppConstants.ToEnumValue(idConverter, mvex.EHBit)}, {CppConstants.ToEnumValue(idConverter, mvex.ConvFn)}, 0x{mvex.InvalidConvFns:X02}, 0x{mvex.InvalidSwizzleFns:X02}, 0x{(uint)mvex.Flags1:X02}, 0x{(uint)mvex.Flags2:X02}),// {idConverter.ToDeclTypeAndValue(def.Code)}");
				}
				writer.WriteLine("};");
				CppConstants.WriteNamespaceEnd(writer, CppConstants.InternalNamespace);
			}
		}

		void GenerateLut((MvexTupleTypeLutKind ttLutKind, EnumValue[] enumValues)[] mvexData, string filename, string tableName) {
			var fullFilename = CppConstants.GetSrcFilename(genTypes, "mvex", filename);
			using (var writer = new FileWriter(TargetLanguage.Cpp, FileUtils.OpenWrite(fullFilename))) {
				writer.WriteFileHeader();
				writer.WriteLine("#include \"internal/mvex/mvex.hpp\"");
				writer.WriteLine();
				CppConstants.WriteNamespaceBegin(writer, CppConstants.InternalNamespace);
				var declTypeStr = mvexData[0].enumValues[0].DeclaringType.Name(idConverter);
				var totalSize = mvexData.Select(x => x.enumValues.Length).Sum();
				writer.WriteLine($"const {declTypeStr} {tableName}[{totalSize}] = {{");
				using (writer.Indent()) {
					foreach (var (ttLutKind, enumValues) in mvexData) {
						var ttLutKindValue = genTypes[TypeIds.MvexTupleTypeLutKind][ttLutKind.ToString()];
						writer.WriteLine($"// {idConverter.ToDeclTypeAndValue(ttLutKindValue)}");
						for (int i = 0; i < enumValues.Length; i++)
							writer.WriteLine($"{CppConstants.ToEnumValue(idConverter, enumValues[i])},// {i}");
					}
				}
				writer.WriteLine("};");
				CppConstants.WriteNamespaceEnd(writer, CppConstants.InternalNamespace);
			}
		}

		protected override void GenerateVsib(EnumValue[] vsib32, EnumValue[] vsib64) {
			var filename = CppConstants.GetSrcFilename(genTypes, "instruction.cpp");
			GenerateCases(filename, "Vsib32", vsib32);
			GenerateCases(filename, "Vsib64", vsib64);
		}

		void GenerateCases(string filename, string id, EnumValue[] codeValues) {
			new FileUpdater(TargetLanguage.Cpp, id, filename).Generate(writer => {
				foreach (var value in codeValues)
					writer.WriteLine($"case {CppConstants.ToEnumValue(idConverter, value)}:");
			});
		}
	}
}
