// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once

#include <cstdint>

namespace iced_x86::internal::intel {

enum class CtorKind : std::uint8_t {
	Previous = 0,
	Normal_1 = 1,
	Normal_2 = 2,
	asz = 3,
	StringIg0 = 4,
	StringIg1 = 5,
	bcst = 6,
	bnd = 7,
	ST2 = 8,
	DeclareData = 9,
	ST_STi = 10,
	STi_ST = 11,
	imul = 12,
	opmask_op = 13,
	invlpga = 14,
	maskmovq = 15,
	memsize = 16,
	movabs = 17,
	nop = 18,
	os2 = 19,
	os3 = 20,
	os_bnd = 21,
	CC_1 = 22,
	CC_2 = 23,
	CC_3 = 24,
	os_jcc_a_1 = 25,
	os_jcc_a_2 = 26,
	os_jcc_a_3 = 27,
	os_jcc_b_1 = 28,
	os_jcc_b_2 = 29,
	os_jcc_b_3 = 30,
	os_loopcc = 31,
	os_loop = 32,
	pclmulqdq = 33,
	pops = 34,
	reg = 35,
	Reg16 = 36,
	Reg32 = 37,
	ST1_2 = 38,
	ST1_3 = 39,
};

} // namespace iced_x86::internal::intel
