// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

#include "internal/formatter/fmt_consts.hpp"

namespace iced_x86::internal {

MvexFormatterConstants::MvexFormatterConstants()
	: swizzle_cdab("cdab")
	, swizzle_badc("badc")
	, swizzle_dacb("dacb")
	, swizzle_aaaa("aaaa")
	, swizzle_bbbb("bbbb")
	, swizzle_cccc("cccc")
	, swizzle_dddd("dddd")
	, mem_1to16("1to16")
	, mem_1to8("1to8")
	, mem_4to16("4to16")
	, mem_4to8("4to8")
	, mem_float16("float16")
	, mem_uint8("uint8")
	, mem_sint8("sint8")
	, mem_uint16("uint16")
	, mem_sint16("sint16")
	, eh("eh") {}

// clang-format off
FormatterConstants::FormatterConstants()
	: empty("")
	// GENERATOR-BEGIN: FormatterConstantsInit
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	, b1to16("1to16")
	, b1to2("1to2")
	, b1to32("1to32")
	, b1to4("1to4")
	, b1to8("1to8")
	, bcst("bcst")
	, byte("byte")
	, dword("dword")
	, far("far")
	, fpuenv14("fpuenv14")
	, fpuenv28("fpuenv28")
	, fpustate108("fpustate108")
	, fpustate94("fpustate94")
	, fword("fword")
	, mem384("mem384")
	, mmword("mmword")
	, oword("oword")
	, ptr("ptr")
	, qword("qword")
	, tbyte("tbyte")
	, tword("tword")
	, word("word")
	, xmmword("xmmword")
	, ymmword("ymmword")
	, yword("yword")
	, zmmword("zmmword")
	, zword("zword")
	// GENERATOR-END: FormatterConstantsInit
	, bnd("bnd")
	, dot_byte(".byte")
	, hint_not_taken("hint-not-taken")
	, hint_taken("hint-taken")
	, hnt("hnt")
	, ht("ht")
	, lock("lock")
	, near("near")
	, notrack("notrack")
	, offset("offset")
	, pn("pn")
	, pt("pt")
	, rel("rel")
	, rep("rep")
	, repe{{FormatterString("repe"), FormatterString("repz")}}
	, repne{{FormatterString("repne"), FormatterString("repnz")}}
	, rex_w("rex.w")
	, rne_sae("rne-sae")
	, rn_sae("rn-sae")
	, rd_sae("rd-sae")
	, ru_sae("ru-sae")
	, rz_sae("rz-sae")
	, sae("sae")
	, rne("rne")
	, rn("rn")
	, rd("rd")
	, ru("ru")
	, rz("rz")
	, short_("short")
	, to("to")
	, xacquire("xacquire")
	, xrelease("xrelease")
	, z("z")
	, a16("a16")
	, a32("a32")
	, a64("a64")
	, addr16("addr16")
	, addr32("addr32")
	, addr64("addr64")
	, data16("data16")
	, data32("data32")
	, data64("data64")
	, o16("o16")
	, o32("o32")
	, o64("o64")
	, mvex() {}
// clang-format on

const FormatterConstants& get_formatter_constants() {
	static const FormatterConstants constants;
	return constants;
}

// clang-format off
FormatterArrayConstants::FormatterArrayConstants(const FormatterConstants& c)
	: nothing{}
	// GENERATOR-BEGIN: FormatterArrayConstantsInit
	// ⚠️This was generated by GENERATOR!🦹‍♂️
	, byte_ptr{{&c.byte, &c.ptr}}
	, dword_bcst{{&c.dword, &c.bcst}}
	, dword_ptr{{&c.dword, &c.ptr}}
	, fpuenv14_ptr{{&c.fpuenv14, &c.ptr}}
	, fpuenv28_ptr{{&c.fpuenv28, &c.ptr}}
	, fpustate108_ptr{{&c.fpustate108, &c.ptr}}
	, fpustate94_ptr{{&c.fpustate94, &c.ptr}}
	, fword_ptr{{&c.fword, &c.ptr}}
	, mem384_ptr{{&c.mem384, &c.ptr}}
	, mmword_ptr{{&c.mmword, &c.ptr}}
	, oword_ptr{{&c.oword, &c.ptr}}
	, qword_bcst{{&c.qword, &c.bcst}}
	, qword_ptr{{&c.qword, &c.ptr}}
	, tbyte_ptr{{&c.tbyte, &c.ptr}}
	, word_bcst{{&c.word, &c.bcst}}
	, word_ptr{{&c.word, &c.ptr}}
	, xmmword_ptr{{&c.xmmword, &c.ptr}}
	, ymmword_ptr{{&c.ymmword, &c.ptr}}
	, zmmword_ptr{{&c.zmmword, &c.ptr}}
	// GENERATOR-END: FormatterArrayConstantsInit
	, gas_op_size_strings{{
		&c.empty,
		&c.data16,
		&c.data32,
		&c.rex_w,
	}}
	, gas_addr_size_strings{{
		&c.empty,
		&c.addr16,
		&c.addr32,
		&c.addr64,
	}}
	, intel_op_size_strings{{
		&c.empty,
		&c.data16,
		&c.data32,
		&c.data64,
	}}
	, intel_addr_size_strings{{
		&c.empty,
		&c.addr16,
		&c.addr32,
		&c.addr64,
	}}
	, intel_rc_strings{{
		&c.empty,
		&c.rne,
		&c.rd,
		&c.ru,
		&c.rz,
	}}
	, intel_rc_sae_strings{{
		&c.empty,
		&c.rne_sae,
		&c.rd_sae,
		&c.ru_sae,
		&c.rz_sae,
	}}
	, intel_branch_infos{{
		{},
		{&c.short_},
	}}
	, masm_rc_strings{{
		&c.empty,
		&c.rn,
		&c.rd,
		&c.ru,
		&c.rz,
	}}
	, masm_rc_sae_strings{{
		&c.empty,
		&c.rn_sae,
		&c.rd_sae,
		&c.ru_sae,
		&c.rz_sae,
	}}
	, nasm_op_size_strings{{
		&c.empty,
		&c.o16,
		&c.o32,
		&c.o64,
	}}
	, nasm_addr_size_strings{{
		&c.empty,
		&c.a16,
		&c.a32,
		&c.a64,
	}}
	, nasm_branch_infos{{
		{},
		{&c.near},
		{&c.near, &c.word},
		{&c.near, &c.dword},
		{&c.word},
		{&c.dword},
		{&c.short_},
		{},
	}}
	, nasm_mem_size_infos{{
		&c.empty,
		&c.word,
		&c.dword,
		&c.qword,
	}}
	, nasm_far_mem_size_infos{{
		&c.empty,
		&c.word,
		&c.dword,
		&c.empty,
	}}
	, mvex_reg_mem_consts_32{{
		&c.empty,
		&c.empty,
		&c.mvex.swizzle_cdab,
		&c.mvex.swizzle_badc,
		&c.mvex.swizzle_dacb,
		&c.mvex.swizzle_aaaa,
		&c.mvex.swizzle_bbbb,
		&c.mvex.swizzle_cccc,
		&c.mvex.swizzle_dddd,
		&c.empty,
		&c.mvex.mem_1to16,
		&c.mvex.mem_4to16,
		&c.mvex.mem_float16,
		&c.mvex.mem_uint8,
		&c.mvex.mem_sint8,
		&c.mvex.mem_uint16,
		&c.mvex.mem_sint16,
	}}
	, mvex_reg_mem_consts_64{{
		&c.empty,
		&c.empty,
		&c.mvex.swizzle_cdab,
		&c.mvex.swizzle_badc,
		&c.mvex.swizzle_dacb,
		&c.mvex.swizzle_aaaa,
		&c.mvex.swizzle_bbbb,
		&c.mvex.swizzle_cccc,
		&c.mvex.swizzle_dddd,
		&c.empty,
		&c.mvex.mem_1to8,
		&c.mvex.mem_4to8,
		&c.mvex.mem_float16,
		&c.mvex.mem_uint8,
		&c.mvex.mem_sint8,
		&c.mvex.mem_uint16,
		&c.mvex.mem_sint16,
	}} {}
// clang-format on

const FormatterArrayConstants& get_array_constants() {
	static const FormatterArrayConstants constants(get_formatter_constants());
	return constants;
}

} // namespace iced_x86::internal
